Add `CopyToClipboard` component
Hunar-ai/hunar-design-system pull request #16
Opened 2024-09-11 07:53 UTC by amar-hunar

This PR adds `CopyToClipboard` component

## Features:

- add `CopyToClipboard` component
- add story for `CopyToClipboard` component

## Technical:

- add code preview for stories (WIP)

2024-09-16 06:56 UTC, misss-popcorn commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +    const copyToClipBoard = async (text: string) => {
usememo

2024-09-16 06:58 UTC, misss-popcorn commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +    showCopiedMsg = false,
```suggestion
    showText = false,
```

2024-09-16 06:59 UTC, misss-popcorn commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +                        {showCopiedMsg && copyMessage}
pls refactor this component instead of just copy pasting it from the dashboard

2024-09-16 06:59 UTC, misss-popcorn commented on src/components/CustomSelect/CustomSelect.stories.tsx
> +                {...props}
why are these changes here?

2024-09-16 06:59 UTC, misss-popcorn commented on src/components/DotDivider/DotDivider.stories.tsx
> +            'Change various props in the "Controls" panel to see how they change behavior of the component',
why are these changes here?

2024-09-16 07:00 UTC, misss-popcorn requested changes
There are unrelated changes in the PR which makes the PR unnecessary long and difficult to review, pls fix

2024-09-16 09:45 UTC, amar-hunar commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +    showCopiedMsg = false,
renamed to `showStatusText` instead

2024-09-16 10:27 UTC, amar-hunar commented on src/components/CustomSelect/CustomSelect.stories.tsx
> +                {...props}
This change is related to adding code-preview for components. Moved this change to PR #18.

2024-09-16 10:27 UTC, amar-hunar commented on src/components/DotDivider/DotDivider.stories.tsx
> +            'Change various props in the "Controls" panel to see how they change behavior of the component',
This change is related to adding code-preview for components. Moved this change to PR #18.

2024-09-17 06:03 UTC, misss-popcorn approved these changes

2024-09-17 08:38 UTC, misss-popcorn commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +            {statusText ? (
pls add condition with showStatusText

2024-09-17 08:38 UTC, misss-popcorn requested changes
Requested 1 more change

2024-09-18 03:17 UTC, amar-hunar commented on src/components/CopyToClipboard/CopyToClipboard.tsx
> +            {statusText ? (
we can't use `showStatusText`. Created another state variable `showStatus`. Using `showStatus` for the condition

2024-09-19 06:36 UTC, misss-popcorn approved these changes

2024-09-19 07:48 UTC, merged